"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p3f#6!^ffk1%l@(owmyz+%57t2hsaqz%zhmaf_u)5d#e8teu(-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third party applar
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',

    # O'zim yaratgan applar
    'users',
    'products',
    'billz',
    'reports',
    'inventory',
    'main'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.joinpath('template')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sales',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432'
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'users.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular (Swagger / OpenAPI)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Sales Management API',
    'DESCRIPTION': (
        'Do\'kon va savdo boshqaruv tizimi uchun REST API.\n\n'
        '**Autentifikatsiya:** Barcha himoyalangan endpointlar uchun '
        '`Authorization: Bearer <access_token>` sarlavhasi talab qilinadi.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'TAGS': [
        {'name': 'Auth',              'description': 'Kirish, chiqish va token boshqaruvi'},
        {'name': 'Branches',          'description': 'Filiallar'},
        {'name': 'Roles',             'description': 'Xodim rollari va ruxsatlar'},
        {'name': 'Users',             'description': 'Foydalanuvchilar (xodimlar)'},
        {'name': 'Sales Targets',     'description': 'Savdo rejalari (plan)'},
        {'name': 'Categories',        'description': 'Mahsulot kategoriyalari (daraxt)'},
        {'name': 'Brands',            'description': 'Brendlar'},
        {'name': 'Units',             'description': "O'lchov birliklari"},
        {'name': 'Product Attributes','description': 'Mahsulot xususiyat turlari'},
        {'name': 'Products',          'description': 'Mahsulotlar katalogi'},
        {'name': 'Product Variants',  'description': 'Mahsulot variantlari (SKU, shtrix-kod)'},
        {'name': 'Price Lists',       'description': "Narxlar ro'yxati"},
        {'name': 'Customer Groups',   'description': 'Mijoz guruhlari (VIP, oddiy va h.k.)'},
        {'name': 'Customers',         'description': 'Mijozlar (CRM)'},
        {'name': 'Cash Registers',    'description': 'Kassalar'},
        {'name': 'Cash Sessions',     'description': 'Kassa smenalari'},
        {'name': 'Sales',             'description': 'Sotuvlar va cheklar'},
        {'name': 'Payment Methods',   'description': "To'lov usullari"},
        {'name': 'Expense Categories','description': 'Xarajat turlari'},
        {'name': 'Expenses',          'description': 'Xarajatlar'},
        {'name': 'Cash Movements',    'description': 'Kassa harakatlari (kirim/chiqim)'},
        {'name': 'Warehouses',        'description': 'Omborxonalar'},
        {'name': 'Stock',             'description': 'Tovar qoldiqlari'},
        {'name': 'Suppliers',         'description': 'Yetkazib beruvchilar'},
        {'name': 'Purchase Orders',   'description': 'Kirim buyurtmalari'},
        {'name': 'Stock Transfers',   'description': "Omborlar o'rtasida tovar ko'chirish"},
        {'name': 'Inventory',         'description': 'Inventarizatsiya (reviziya)'},
        {'name': 'Write-offs',        'description': 'Hisobdan chiqarishlar'},
    ],
}

# Simple JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
